namespace ItemStockRepoPattern.View.Forms
{
	partial class testfrom
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
			this.Root = new DevExpress.XtraLayout.LayoutControlGroup();
			this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.itemNameTextEdit = new DevExpress.XtraEditors.TextEdit();
			this.ItemForitemName = new DevExpress.XtraLayout.LayoutControlItem();
			this.itemPriceTextEdit = new DevExpress.XtraEditors.TextEdit();
			this.ItemForitemPrice = new DevExpress.XtraLayout.LayoutControlItem();
			this.itemPriceSingleTextEdit = new DevExpress.XtraEditors.TextEdit();
			this.ItemForitemPriceSingle = new DevExpress.XtraLayout.LayoutControlItem();
			this.itemModelBindingSource = new System.Windows.Forms.BindingSource(this.components);
			((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
			this.dataLayoutControl1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.Root)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.itemNameTextEdit.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemName)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.itemPriceTextEdit.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemPrice)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.itemPriceSingleTextEdit.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemPriceSingle)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.itemModelBindingSource)).BeginInit();
			this.SuspendLayout();
			// 
			// dataLayoutControl1
			// 
			this.dataLayoutControl1.Controls.Add(this.itemNameTextEdit);
			this.dataLayoutControl1.Controls.Add(this.itemPriceTextEdit);
			this.dataLayoutControl1.Controls.Add(this.itemPriceSingleTextEdit);
			this.dataLayoutControl1.DataSource = this.itemModelBindingSource;
			this.dataLayoutControl1.Location = new System.Drawing.Point(255, 114);
			this.dataLayoutControl1.Name = "dataLayoutControl1";
			this.dataLayoutControl1.Root = this.Root;
			this.dataLayoutControl1.Size = new System.Drawing.Size(180, 120);
			this.dataLayoutControl1.TabIndex = 0;
			this.dataLayoutControl1.Text = "dataLayoutControl1";
			// 
			// Root
			// 
			this.Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
			this.Root.GroupBordersVisible = false;
			this.Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup1,
            this.ItemForitemName});
			this.Root.Name = "Root";
			this.Root.Size = new System.Drawing.Size(180, 120);
			this.Root.TextVisible = false;
			// 
			// layoutControlGroup1
			// 
			this.layoutControlGroup1.AllowDrawBackground = false;
			this.layoutControlGroup1.GroupBordersVisible = false;
			this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.ItemForitemPrice,
            this.ItemForitemPriceSingle});
			this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
			this.layoutControlGroup1.Name = "autoGeneratedGroup0";
			this.layoutControlGroup1.Size = new System.Drawing.Size(160, 48);
			// 
			// itemNameTextEdit
			// 
			this.itemNameTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.itemModelBindingSource, "itemName", true));
			this.itemNameTextEdit.Location = new System.Drawing.Point(101, 60);
			this.itemNameTextEdit.Name = "itemNameTextEdit";
			this.itemNameTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
			this.itemNameTextEdit.Size = new System.Drawing.Size(67, 20);
			this.itemNameTextEdit.StyleController = this.dataLayoutControl1;
			this.itemNameTextEdit.TabIndex = 4;
			// 
			// ItemForitemName
			// 
			this.ItemForitemName.Control = this.itemNameTextEdit;
			this.ItemForitemName.Location = new System.Drawing.Point(0, 48);
			this.ItemForitemName.Name = "ItemForitemName";
			this.ItemForitemName.Size = new System.Drawing.Size(160, 52);
			this.ItemForitemName.TextSize = new System.Drawing.Size(77, 13);
			// 
			// itemPriceTextEdit
			// 
			this.itemPriceTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.itemModelBindingSource, "itemPrice", true));
			this.itemPriceTextEdit.Location = new System.Drawing.Point(101, 12);
			this.itemPriceTextEdit.Name = "itemPriceTextEdit";
			this.itemPriceTextEdit.Properties.Appearance.Options.UseTextOptions = true;
			this.itemPriceTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
			this.itemPriceTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
			this.itemPriceTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.NumericMaskManager));
			this.itemPriceTextEdit.Properties.MaskSettings.Set("mask", "G");
			this.itemPriceTextEdit.Size = new System.Drawing.Size(67, 20);
			this.itemPriceTextEdit.StyleController = this.dataLayoutControl1;
			this.itemPriceTextEdit.TabIndex = 5;
			// 
			// ItemForitemPrice
			// 
			this.ItemForitemPrice.Control = this.itemPriceTextEdit;
			this.ItemForitemPrice.Location = new System.Drawing.Point(0, 0);
			this.ItemForitemPrice.Name = "ItemForitemPrice";
			this.ItemForitemPrice.Size = new System.Drawing.Size(160, 24);
			this.ItemForitemPrice.Text = "item Price";
			this.ItemForitemPrice.TextSize = new System.Drawing.Size(77, 13);
			// 
			// itemPriceSingleTextEdit
			// 
			this.itemPriceSingleTextEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.itemModelBindingSource, "itemPriceSingle", true));
			this.itemPriceSingleTextEdit.Location = new System.Drawing.Point(101, 36);
			this.itemPriceSingleTextEdit.Name = "itemPriceSingleTextEdit";
			this.itemPriceSingleTextEdit.Properties.Appearance.Options.UseTextOptions = true;
			this.itemPriceSingleTextEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
			this.itemPriceSingleTextEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
			this.itemPriceSingleTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.NumericMaskManager));
			this.itemPriceSingleTextEdit.Properties.MaskSettings.Set("mask", "G");
			this.itemPriceSingleTextEdit.Size = new System.Drawing.Size(67, 20);
			this.itemPriceSingleTextEdit.StyleController = this.dataLayoutControl1;
			this.itemPriceSingleTextEdit.TabIndex = 6;
			// 
			// ItemForitemPriceSingle
			// 
			this.ItemForitemPriceSingle.Control = this.itemPriceSingleTextEdit;
			this.ItemForitemPriceSingle.Location = new System.Drawing.Point(0, 24);
			this.ItemForitemPriceSingle.Name = "ItemForitemPriceSingle";
			this.ItemForitemPriceSingle.Size = new System.Drawing.Size(160, 24);
			this.ItemForitemPriceSingle.Text = "item Price Single";
			this.ItemForitemPriceSingle.TextSize = new System.Drawing.Size(77, 13);
			// 
			// itemModelBindingSource
			// 
			this.itemModelBindingSource.DataSource = typeof(ItemStockRepoPattern.Model.ItemModel);
			// 
			// testfrom
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(963, 777);
			this.Controls.Add(this.dataLayoutControl1);
			this.Name = "testfrom";
			this.Text = "testfrom";
			this.Load += new System.EventHandler(this.testfrom_Load);
			((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
			this.dataLayoutControl1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.Root)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.itemNameTextEdit.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemName)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.itemPriceTextEdit.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemPrice)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.itemPriceSingleTextEdit.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForitemPriceSingle)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.itemModelBindingSource)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
		private DevExpress.XtraLayout.LayoutControlGroup Root;
		private System.Windows.Forms.BindingSource itemModelBindingSource;
		private DevExpress.XtraEditors.TextEdit itemNameTextEdit;
		private DevExpress.XtraEditors.TextEdit itemPriceTextEdit;
		private DevExpress.XtraEditors.TextEdit itemPriceSingleTextEdit;
		private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
		private DevExpress.XtraLayout.LayoutControlItem ItemForitemName;
		private DevExpress.XtraLayout.LayoutControlItem ItemForitemPrice;
		private DevExpress.XtraLayout.LayoutControlItem ItemForitemPriceSingle;
	}
}