using System;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using NewStock.Logic;
using NewStock.Logic.Services;

namespace NewStock.Forms
{
	public partial class Bill : XtraForm
	{
		public Bill()
		{
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
		}

		private void setData()
		{
			gridControl1.DataSource = BillService.GetData();
		}

		private void Bill_Load(object sender, EventArgs e)
		{
			setData();
		}

		private void gridView1_RowClick(object sender, RowClickEventArgs e)
		{
			SaveGuid.guidSave = new Guid
				(gridView1.GetFocusedRowCellValue("BillGuid").ToString());
			var form = new Frm_Bills();
			form.ShowDialog();
			form.Close();
			setData();
		}
	}
}