namespace NewStock.Forms
{
	public partial class Frm_Item : DevExpress.XtraEditors.XtraForm
	{
		public Frm_Item()
		{
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			tB_ItemTableAdapter1.Fill(billsDB1.TB_Item);
		}
	}
}