using NewStock.Logic;
using System;

namespace NewStock.Forms
{
	public partial class Frm_Item : DevExpress.XtraEditors.XtraForm
	{
		public Frm_Item()
		{
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			tB_ItemTableAdapter1.Fill(billsDB1.TB_Item);

		}



		private void treeList1_DoubleClick(object sender, EventArgs e)
		{
			SaveGuid.guidSave = new Guid
				(treeList1.GetFocusedRowCellValue("itemGuid").ToString());
			var form = new Frm_ItemForms();
			form.ShowDialog();
			form.Close();
			tB_ItemTableAdapter1.Fill(billsDB1.TB_Item);
		}
	}
}